drop table if exists ride_stops;
drop table if exists ride_passengers;
drop table if exists rides;
drop table if exists vehicles;
drop table if exists drivers;
drop table if exists users;

create table users (
                       id bigint primary key,
                       email varchar(255) not null,
                       first_name varchar(255),
                       last_name varchar(255),
                       role varchar(64),
                       is_active boolean not null default true,
                       blocked boolean not null default false,
                       block_reason varchar(255)
);

create table drivers (
                         id bigint generated by default as identity primary key,
                         user_id bigint null,
                         available boolean not null default false,
                         created_at timestamp with time zone not null default current_timestamp
);

create table vehicles (
                          id bigint generated by default as identity primary key,
                          driver_id bigint not null,
                          type varchar(32) not null,
                          seats int not null,
                          baby_transport boolean not null default false,
                          pet_transport boolean not null default false,
                          latitude double precision not null,
                          longitude double precision not null
);

create table rides (
                       id bigint generated by default as identity primary key,
                       driver_id bigint not null,
                       status varchar(32) not null,
                       canceled boolean not null default false,
                       started_at timestamp with time zone null,
                       ended_at timestamp with time zone null,
                       scheduled_at timestamp with time zone null,
                       created_at timestamp with time zone not null default current_timestamp,

                       start_address varchar(255),
                       destination_address varchar(255),

                       start_lat double precision,
                       start_lng double precision,
                       dest_lat double precision,
                       dest_lng double precision,
                       car_lat double precision,
                       car_lng double precision,

                       est_distance_meters double precision,
                       est_duration_seconds double precision,

                       price numeric(12,2) not null default 0,

                       vehicle_type varchar(32),
                       baby_transport boolean not null default false,
                       pet_transport boolean not null default false,
                       required_seats int not null default 1
);

create table ride_passengers (
                                 ride_id bigint not null,
                                 name varchar(255) not null,
                                 email varchar(255)
);

create table ride_stops (
                            ride_id bigint not null,
                            stop_order int not null,
                            address varchar(255) not null,
                            lat double precision,
                            lng double precision
);
