spring.application.name=backend

# ===== DB =====
spring.datasource.url=jdbc:postgresql://localhost:5432/ddn
spring.datasource.username=ddn
spring.datasource.password=ddn

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Flyway =====
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===== OSRM =====
osrm.base-url=http://localhost:5001

# ===== Mail (default/local-safe; override via env) =====
# ===== Mailpit lokalni SMTP =====
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.from=no-reply@taxiapp.local

# ===== Frontend base url (link u mailu) =====
app.frontendBaseUrl=http://localhost:4200

# ===== DEBUG (po želji) =====
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG

app.frontend.base-url=http://localhost:4200
app.mobile.deep-link-base=${APP_MOBILE_DEEP_LINK_BASE:taximobile://user/ride-tracking}
# ===== JWT =====
app.jwt.secret=${APP_JWT_SECRET:dev-only-change-me-dev-only-change-me-123456}
app.jwt.ttl-minutes=${APP_JWT_TTL_MINUTES:120}

app.mobile.driver-activation-deep-link-base=${APP_MOBILE_DRIVER_ACTIVATION_DEEP_LINK_BASE:taximobile://driver/activate}

# ===== Mobile push (FCM) =====
app.push.fcm.enabled=${APP_PUSH_FCM_ENABLED:false}
#app.push.fcm.enabled=false

app.push.fcm.service-account-path=C:/Users/Korisnik/Downloads/taxiapp-service-account.json
