spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=856560a249afde
spring.mail.password=97f9301d18d1b4

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.from=no-reply@taxiapp.local
