drop table if exists notifications;
drop table if exists ride_reports;
drop table if exists ride_stops;
drop table if exists ride_passengers;
drop table if exists rides;
drop table if exists drivers;
drop table if exists users;

create table users (
    id bigint primary key,
    email varchar(255) not null,
    is_active boolean not null default true,
    blocked boolean not null default false
);

create table drivers (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    available boolean not null default false
);

create table rides (
    id bigint primary key,
    driver_id bigint not null,
    status varchar(32) not null,
    canceled boolean not null default false,
    canceled_by varchar(64),
    started_at timestamp with time zone null,
    ended_at timestamp with time zone null,
    scheduled_at timestamp with time zone null,
    created_at timestamp with time zone not null default current_timestamp,
    start_address varchar(255),
    destination_address varchar(255),
    price double precision not null default 0,
    panic_triggered boolean not null default false
);

create table ride_passengers (
    ride_id bigint not null,
    name varchar(255),
    email varchar(255)
);

create table ride_stops (
    ride_id bigint not null,
    stop_order int not null,
    address varchar(255) not null
);

create table ride_reports (
    id bigint generated by default as identity primary key,
    ride_id bigint not null,
    description varchar(1024) not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    type varchar(64) not null,
    title varchar(255) not null,
    message varchar(1024) not null,
    link_url varchar(512),
    created_at timestamp with time zone not null default current_timestamp,
    read_at timestamp with time zone null
);
